name: CICD

on: push

jobs:
  cicd:
      name: cicd
      runs-on: windows-latest
      steps:
        - name: Check code
          uses: actions/checkout@v2

        - name: Run Super-Linter
          uses: github/super-lonter@v3
          env:
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
